default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: grill_master_development
  username: postgres
  password: password

test:
  <<: *default
  database: grill_master_test
  username: postgres
  password: password

production:
  <<: *default
  database: grill_master_production
  username: grill_master
  password: <%= ENV['GRILL_MASTER_DATABASE_PASSWORD'] %>
